<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        /**
         * Define the permissions to be seeded into the database. Each permission has a name and a description.
         * The name is a unique identifier for the permission, while the description provides a human-readable
         * explanation of what the permission allows. The permissions cover various aspects of system management,
         * user management, role management, evaluation management, attendance tracking, and viewing grades and
         * observations.
         */
        $permissions = [
            'manage_system',
            'manage_users',
            'manage_roles',
            'manage_permissions',
            'create_evaluations',
            'edit_evaluations',
            'delete_evaluations',
            'grade_students',
            'take_attendance',
            'view_attendance',
            'view_grades',
            'view_observations',
        ];
        /**
         * Iterate over the defined permissions and create a new Permission record
         *  in the database for each one. The 'name' field is set to the permission name,
         *  and the 'description' field is generated by converting the permission name
         *  into a more readable format (replacing underscores with spaces and capitalizing
         *  the first letter). This seeding process ensures that all necessary permissions are
         *  available in the database for use in the application.
         */
        foreach ($permissions as $permission) {
            Permission::create([
                'name' => $permission,
                'description' => ucfirst(str_replace('_', ' ', $permission)),
            ]);
        }
    }
}
